yolov5:
  path: /home/eric/a_ros_ws/object_dection_ws/src/3d-object-detection/yolo_ros
  weight: /home/eric/a_ros_ws/object_dection_ws/src/3d-object-detection/yolo_ros/scripts/yolov5s.pt
  device: gpu
  image_topic: /usb_cam/image_raw
  img_size: 640
